// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "myserver_handler.h"
#include "boost/shared_ptr.hpp"
#include "boost/bind.hpp"

using namespace  ::myserver;

MyServerHandler::MyServerHandler() 
	: m_work(m_io_service)
	, m_strand(m_io_service)
{
    // Your initialization goes here
}

bool MyServerHandler::start()
{
	for (int i = 0; i < 10; i++)
	{
		m_thread_group.create_thread(boost::bind(&boost::asio::io_service::run, m_io_service));
	}
	return true;
}

void MyServerHandler::stop()
{
}

void MyServerHandler::timer_handler()
{
}

void MyServerHandler::login(Response& _return, const LoginRequest& req) 
{
    // Your implementation goes here
    printf("login\n");
}

void MyServerHandler::logout(Response& _return, const Request& req)
{
	// Your implementation goes here
    printf("logout\n");
}
