version: '3'
services:
  envoy:
    image: envoyproxy/envoy:dev-5880c2d25399566a5376c274817ba9d86d2091a8
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy-my.yaml:/etc/envoy/envoy.yaml