// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "./gen-cpp/MyServer.h"
#include "boost/asio.hpp"
#include "boost/thread.hpp"

using namespace  ::myserver;

class MyServerHandler : virtual public MyServerIf 
{
public:
	MyServerHandler();
	~MyServerHandler();

	bool start();
	void stop();

	void run();

	void timer_handler();

	void login(Response& _return, const LoginRequest& req);

	void logout(Response& _return, const Request& req);

private:
	boost::asio::io_service m_io_service;
	boost::asio::io_service::work m_work;
	boost::asio::io_service::strand m_strand;
	boost::thread_group m_thread_group;
    boost::asio::deadline_timer timer_;
};

